### ISSUE TITLE
[race] Implement a Race object

### ISSUE THREAD

**Issue by joelalejandro** [xethya/framework#14]
According to the [Race](https://www.dandwiki.com/wiki/5e_SRD:About_Races) specs from the SRD, a Race has the following properties:

### Ability Score Increase
Every race increases one or more of a character's ability scores.

### Age
The age entry notes the age when a member of the race is considered an adult, as well as the race's expected lifespan. This information can help you decide how old your character is at the start of the game. You can choose any age for your character, which could provide an explanation for some of your ability scores. For example, if you play a young or very old character, your age could explain a particularly low Strength or Constitution score, while advanced age could account for a high Intelligence or Wisdom.

### Alignment
Most races have tendencies toward certain alignments, described in this entry. These are not binding for player characters, but considering why your dwarf is chaotic, for example, in defiance of lawful dwarf society can help you better define your character.

### Size
Characters of most races are Medium, a size category including creatures that are roughly 4 to 8 feet tall. Members of a few races are Small (between 2 and 4 feet tall), which means that certain rules of the game affect them differently. The most important of these rules is that Small characters have trouble wielding heavy weapons, as explained in “Equipment.”

### Speed
Your speed determines how far you can move when traveling (“Adventuring”) and fighting (“Combat”).

### Languages
By virtue of your race, your character can speak, read, and write certain languages.

### Subraces
Some races have subraces. Members of a subrace have the traits of the parent race in addition to the traits specified for their subrace. Relationships among subraces vary significantly from race to race and world to world.

## Tasks
- [x] Create `Alignment` enum
- [x] Create `Size` enum
- [ ] Implement the object
